services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      #DATABASE_CONNECTION_URI: "jdbc:h2:~/test"
      DATABASE_CONNECTION_URI: "jdbc:postgresql://db/"
      #?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
      DATABASE_USER: "ideabox"
      DATABASE_PASSWORD: "ideabox"
    depends_on:
      - db
  db:
    image: postgres:16.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "ideabox"
      POSTGRES_PASSWORD: "ideabox"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local


