CREATE TABLE IF NOT EXISTS ideas (
       id UUID NOT NULL PRIMARY KEY,
       title VARCHAR(255) NOT NULL,
       description VARCHAR(4000) NOT NULL,
       created_at TIMESTAMP NOT NULL DEFAULT NOW(),
       updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE IF EXISTS ideas ADD COLUMN IF NOT EXISTS rank SMALLINT DEFAULT 0;

CREATE INDEX IF NOT EXISTS ideas_rank ON ideas (rank);

ALTER TABLE IF EXISTS ideas ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS ideas_archived ON ideas (archived);

CREATE TABLE IF NOT EXISTS users (
       id UUID NOT NULL PRIMARY KEY,
       username VARCHAR(64) NOT NULL,
       email VARCHAR(64) NOT NULL,
       password VARCHAR(128) NOT NULL,
       created_at TIMESTAMP NOT NULL DEFAULT NOW(),
       updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE IF EXISTS users ADD CONSTRAINT IF NOT EXISTS users_email_uk UNIQUE (email);

ALTER TABLE IF EXISTS ideas ADD COLUMN IF NOT EXISTS user_id UUID;

ALTER TABLE IF EXISTS ideas ADD CONSTRAINT IF NOT EXISTS idea_user_fk FOREIGN KEY (user_id) REFERENCES users (id);
